spring:
  application:
    name: ai-ms

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

claude:
  api:
    key: ${CLAUDE_API_KEY}
    url: https://api.anthropic.com/v1/messages
    model: claude-sonnet-4-20250514
    version: 2023-06-01
